---
- hosts: local
  tasks:
  - name: Set Hostname
    hostname:
      name: "{{ host_name }}"
  - name: Add group staffs
    group:
      name: staffs
  - name: Add the user 'mac' and 'bob'
    user:
      name: "{{ item }}"
      group: staffs
    loop:
      - mac
      - bob
  - name: install the dummy rpm from a local path
    yum:
      name: /rpmbuild/RPMS/noarch/my-monitoring-agent-1.0-1.noarch.rpm
      state: present
  - name: Create directory /etc/mon-agent/
    directory:
      file: path=/etc/mon-agent/ state=directory
      mode: 0755
  - name: Template replaces /etc/mon-agent/agent.config
    template:
      src: agent.config.j2
      dest: /etc/mon-agent/agent.config
