---
- name: Install htpd on all the nodes
  hosts: ansiblenode1
  tasks:
   - name: check the package
     command: "rpm -qa httpd"
     var: rpm_out
   - name: Install httpd
     yum:
      name: httpd
      state: latest
     when: rpm_out.stdout == ""
     notify:
       - service
  handlers:
   - name: start the service
     service:
      name: httpd
      state: restarted
     register: service_state
     listen: service
   - debug:
      var: var1
   - debug:
      msg: "Restart sucess"
     when: service_State != ""
     listen: service
        
