---
- name: Create BES with extended backend parameters
  hosts: all
  gcp_backend_service:
    service_account_email: "111111111-compute@developer.gserviceaccount.com"
    credentials_file: "/home/aditya/gce-default.json"
    project_id: "logical-bolt-1111"
    backend_service_name: service1
    backends:
    - instance_group: ansible-mig-example
      zone: us-west1-c
    healthchecks:
    - name: my-healthcheck
    port_name: http
    state: present
    timeout: 60
